spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test3
    username: sa
    password:
    driver-class-name : org.h2.Driver

  jpa:
    hibernate:
      ddl-auto : create #자동으로 DB 생성
    properties:
      hibernate:
#        show_sql: true #systemout으로 로그 찍힘
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug #JPA hibernate가 생성하는 SQL 보임


feign:
  client:
    config:
      default:
        #        loggerLevel: FULL
        connectTimeout: 5000
        readTimeout: 5000
  httpclient:
    disable-ssl-validation: true

endpoint:
  kakao:
    host: https://dapi.kakao.com
  naver:
    host: localhost:3003/naver/