spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test3
    username: sa
    password:
    driver-class-name : org.h2.Driver

  jpa:
    hibernate:
      ddl-auto : none #자동으로 DB 생성 update: 더이상 바꾸고 싶지 않을 때, # create: 자동 갱신
    properties:
      hibernate:
#        show_sql: true #systemout으로 로그 찍힘
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: debug #JPA hibernate가 생성하는 SQL 보임


feign:
  client:
    config:
      default:
        #        loggerLevel: FULL
        connectTimeout: 5000
        readTimeout: 5000
  httpclient:
    disable-ssl-validation: true

endpoint:
  kakao:
    restApiKey: KakaoAK 0843e64cd14a049e15aea40c5451f049
    host: https://dapi.kakao.com
  naver:
    clientId: W4ltIYBe53CA8UymY6Ge
    clientSecret: fNctmFMBfq
    host: https://openapi.naver.com